routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Master\DepartmentController;
use App\Http\Controllers\Master\FileTypeController;
use App\Http\Controllers\Master\FinancialYearController;
use App\Http\Controllers\Master\MethodController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\DMCFilePermissionController;
use App\Http\Controllers\DepartmentFileController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest', 'PreventBackHistory', 'firewall.all'])->group(function () {
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'])->name('register');
    Route::post('register', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');
});




// Authenticated users
Route::middleware(['auth', 'PreventBackHistory', 'firewall.all'])->group(function () {

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'])->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'])->name('change-password');




    // Users Roles n Permissions
    Route::resource('users', App\Http\Controllers\Admin\UserController::class);
    Route::get('users/{user}/toggle', [App\Http\Controllers\Admin\UserController::class, 'toggle'])->name('users.toggle');
    Route::get('users/{user}/retire', [App\Http\Controllers\Admin\UserController::class, 'retire'])->name('users.retire');
    Route::put('users/{user}/change-password', [App\Http\Controllers\Admin\UserController::class, 'changePassword'])->name('users.change-password');
    Route::get('users/{user}/get-role', [App\Http\Controllers\Admin\UserController::class, 'getRole'])->name('users.get-role');
    Route::put('users/{user}/assign-role', [App\Http\Controllers\Admin\UserController::class, 'assignRole'])->name('users.assign-role');
    Route::resource('roles', App\Http\Controllers\Admin\RoleController::class);

    // Route for master
    Route::name('master.')->prefix('master/')->group(function () {
        Route::resource('department', DepartmentController::class);
        Route::resource('file-type', FileTypeController::class);
        Route::resource('financial-year', FinancialYearController::class);
        Route::resource('method', MethodController::class);
    });

    // file Route for forward
    Route::get('file/forward/get-department', [FileController::class, 'getForwardDepartment'])->name('file.forward-department');
    Route::get('file/forward/get-department-user', [FileController::class, 'getForwardDepartmentUser'])->name('file.forward-department-user');
    Route::get('file/forward/get-administrative-user', [FileController::class, 'getForwardAdministrativeUser'])->name('file.forward-administrative-user');
    Route::get('file/forward', [FileController::class, 'forward'])->name('file.forward');
    Route::get('file/show-forward-details', [FileController::class, 'showForwardDetails'])->name('files.showForwardDetails');
    Route::post('file/forward/store', [FileController::class, 'storeForward'])->name('file.storeForward');

    // file route for inward
    Route::get('file/inward', [FileController::class, 'inward'])->name('file.inward');
    Route::get('file/show-inward-details', [FileController::class, 'showInwardDetails'])->name('files.showInwardDetails');
    Route::post('file/inward/store', [FileController::class, 'storeInward'])->name('file.storeInward');

    // dmc file route
    Route::get('file/dmc/verify', [DMCFilePermissionController::class, 'index'])->name('dmcfile.index');
    Route::post('file/dmc-file/store', [DMCFilePermissionController::class, 'store'])->name('dmcfile.store');
    Route::get('file/dmc/verified', [DMCFilePermissionController::class, 'verified'])->name('dmcfile.verified');
    Route::get('file/dmc/rejected', [DMCFilePermissionController::class, 'rejected'])->name('dmcfile.rejected');

    // route for close file
    Route::get('file/close', [FileController::class, 'close'])->name('file.close');
    Route::post('file/close/store', [FileController::class, 'saveClose'])->name('file.saveClose');

    // file route for create
    Route::get('file/show-details', [FileController::class, 'showDetails'])->name('files.showDetails');
    Route::get('file/transit', [FileController::class, 'transit'])->name('files.transit');
    Route::get('file/qrcode', [FileController::class, 'qrCode'])->name('files.qrCode');
    Route::resource('file', FileController::class);

    // route for department file
    Route::get('department-files', [DepartmentFileController::class, 'getUserDepartmentFiles'])->name('department.getUserDepartmentFiles');

    // route for report
    Route::get('report/department', [ReportController::class, 'department'])->name('report.department');
    Route::get('report/employee', [ReportController::class, 'employee'])->name('report.employee');
    Route::get('report/file-status', [ReportController::class, 'fileStatus'])->name('report.fileStatus');
});




Route::get('/php', function (Request $request) {
    if (!auth()->check())
        return 'Unauthorized request';

    Artisan::call($request->artisan);
    return dd(Artisan::output());
});

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Auth;
use App\Models\File;
use App\Models\UserDepartment;

class DashboardController extends Controller
{

    public function index()
    {
        $role = Auth::user()->roles[0]->name;
        if($role == 'Administrative DMC'){
            $userDepartments = UserDepartment::where('user_id', Auth::user()->id)->pluck('department_id')->toArray();

            $totalFile = File::whereNotNull('dmc_status')->whereIn('department_id', $userDepartments)->count();

            $totalVerifyFile = File::where('dmc_status', "0")->whereIn('department_id', $userDepartments)->count();

            $totalVerifiedFile = File::where('dmc_status', "2")->whereIn('department_id', $userDepartments)->count();

            $totalRejectedFile = File::where('dmc_status', "1")->whereIn('department_id', $userDepartments)->count();

            $files = File::with(['fileType'])->whereNotNull('dmc_status')->whereIn('department_id', $userDepartments)->latest()->limit(5)->get();

            return view('dashboard.dmc-dashboard')->with([
                'totalFile' => $totalFile,
                'totalVerifyFile' => $totalVerifyFile,
                'totalVerifiedFile' => $totalVerifiedFile,
                'totalRejectedFile' => $totalRejectedFile,
                'files' => $files
            ]);
        }else{
            $totalFile = File::where('user_id', Auth::user()->id)->count();

            $totalCreatedFile = File::where('user_id', Auth::user()->id)->where('is_file_forward', 0)->count();

            $totalCloseFile = File::where('user_id', Auth::user()->id)->where('is_close', 1)->count();

            $totalForwardFile = File::where([
                'user_id' => Auth::user()->id,
                'is_close' => 0,
                'is_file_forward' => 1
                ])->count();

            $totalAcceptedFileByDmc = File::where(['user_id' => Auth::user()->id, 'dmc_status' => "2"])->count();

            $totalRejectedFileByDmc = File::where(['user_id' => Auth::user()->id, 'dmc_status' => "1"])->count();

            $files = File::with(['fileType'])->where('user_id', Auth::user()->id)->latest()->limit(5)->get();

            return view('dashboard.dashboard')->with([
                'totalFile' => $totalFile,
                'totalAcceptedFileByDmc' => $totalAcceptedFileByDmc,
                'totalRejectedFileByDmc' => $totalRejectedFileByDmc,
                'files' => $files,
                'totalCloseFile' => $totalCloseFile,
                'totalForwardFile' => $totalForwardFile,
                'totalCreatedFile' => $totalCreatedFile
            ]);
        }

    }

    public function changeThemeMode()
    {
        $mode = request()->cookie('theme-mode');

        if ($mode == 'dark')
            Cookie::queue('theme-mode', 'light', 43800);
        else
            Cookie::queue('theme-mode', 'dark', 43800);

        return true;
    }
}

resources/views/dashboard/dashboard.blade.php
<x-admin.layout>
    <x-slot name="title">Dashboard</x-slot>
    <x-slot name="heading">Dashboard</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}

    <div class="row">
        <div class="col-lg-6 col-md-6 col-12">
            <div class="d-flex flex-column h-100">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-info">
                            <div class="card-body">
                                <a href="javascript:void(0)">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalFile }}">{{ $totalFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-warning">
                            <div class="card-body">
                                <a href="{{ route('file.index') }}">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total Created File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalCreatedFile }}">{{ $totalCreatedFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-secondary">
                            <div class="card-body">
                                <a href="{{ route('files.transit') }}">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total Transit File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalForwardFile }}">{{ $totalForwardFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-primary">
                            <div class="card-body">
                                <a href="{{ route('file.close') }}">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total Closed File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalCloseFile }}">{{ $totalCloseFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>

                    <!-- end col-->
                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-success">
                            <div class="card-body">
                                <a href="javascript:void(0)">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total File Accepted By DMC
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalAcceptedFileByDmc }}">{{ $totalAcceptedFileByDmc }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-danger">
                            <div class="card-body">
                                <a href="javascript:void(0)">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total File Rejected By DMC
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalRejectedFileByDmc }}">{{ $totalRejectedFileByDmc }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-12">
            <div class="card border-primary card-height-100">

                <div class="card-header bg-primary align-items-center d-flex">
                    <h4 class="card-title text-white mb-0 flex-grow-1">Latest File List</h4>
                    <div class="flex-shrink-0">
                        <a href="{{ route('file.index') }}" class="btn btn-warning btn-sm">
                            View All
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example1"
                            class="table table-bordered nowrap align-middle"
                            style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr.No.</th>
                                    <th>File No.</th>
                                    <th>Date</th>
                                    <th>File Type</th>
                                    <th>Subject</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($files as $file)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $file->file_no }}</td>
                                    <td>{{ date('d-m-Y', strtotime($file->date)) }}</td>
                                    <td>{{ $file?->fileType->name }}</td>
                                    <td>{{ $file->subject }}</td>
                                    <td>
                                        @if($file->is_file_forward == "0" && $file->is_close == "0")
                                        <span class="badge bg-warning text-dark">Pending</span>
                                        @elseif($file->is_file_forward == "1" && $file->is_close == "0")
                                        <span class="badge bg-info text-dark">Intransit</span>
                                        @elseif($file->is_file_forward == "1" && $file->is_close == "1")
                                        <span class="badge bg-success text-dark">Closed</span>
                                        @endif
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="7" align="center">No Data Found</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>



    @push('scripts')
    @endpush

</x-admin.layout>

resources/views/dashboard/dmc-dashboard.blade.php
<x-admin.layout>
    <x-slot name="title">Dashboard</x-slot>
    <x-slot name="heading">Dashboard</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}

    <div class="row">
        <div class="col-lg-6 col-md-6 col-12">
            <div class="d-flex flex-column h-100">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-info">
                            <div class="card-body">
                                <a href="javascript:void(0)">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalFile }}">{{ $totalFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-secondary">
                            <div class="card-body">
                                <a href="{{ route('dmcfile.index') }}">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total Verify File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalVerifyFile }}">{{ $totalVerifyFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-success">
                            <div class="card-body">
                                <a href="{{ route('dmcfile.verified') }}">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total Verified File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalVerifiedFile }}">{{ $totalVerifiedFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                    <div class="col-md-6 col-sm-6 col-12 col-lg-6">
                        <div class="card card-animate bg-danger">
                            <div class="card-body">
                                <a href="{{ route('dmcfile.rejected') }}">
                                    <div class="text-center">
                                        <p class="fw-medium text-white mb-0">
                                            Total Rejected File
                                        </p>
                                        <h2 class="mt-2 ff-secondary fw-semibold">
                                            <span class="counter-value text-white" data-target="{{ $totalRejectedFile }}">{{ $totalRejectedFile }}</span>
                                        </h2>
                                    </div>

                                </a>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card-->
                    </div>
                    <!-- end col-->

                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-12">
            <div class="card border-primary card-height-100">

                <div class="card-header bg-primary align-items-center d-flex">
                    <h4 class="card-title text-white mb-0 flex-grow-1">Latest File List</h4>
                    <div class="flex-shrink-0">
                        <a href="{{ route('dmcfile.index') }}" class="btn btn-warning btn-sm">
                            View All
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example1"
                            class="table table-bordered nowrap align-middle"
                            style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr.No.</th>
                                    <th>File No.</th>
                                    <th>Date</th>
                                    <th>File Type</th>
                                    <th>Subject</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($files as $file)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $file->file_no }}</td>
                                    <td>{{ date('d-m-Y', strtotime($file->date)) }}</td>
                                    <td>{{ $file?->fileType->name }}</td>
                                    <td>{{ $file->subject }}</td>
                                    <td>
                                        @if($file->dmc_status == "0")
                                        <span class="badge bg-warning text-dark">Pending</span>
                                        @elseif($file->dmc_status == "1")
                                        <span class="badge bg-danger text-dark">Rejected</span>
                                        @elseif($file->dmc_status == "2")
                                        <span class="badge bg-success text-dark">Accepted</span>
                                        @endif
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="7" align="center">No Data Found</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>



    @push('scripts')
    @endpush

</x-admin.layout>