routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Master\DepartmentController;
use App\Http\Controllers\Master\FileTypeController;
use App\Http\Controllers\Master\FinancialYearController;
use App\Http\Controllers\Master\MethodController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\DMCFilePermissionController;
use App\Http\Controllers\DepartmentFileController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest', 'PreventBackHistory', 'firewall.all'])->group(function () {
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'])->name('register');
    Route::post('register', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');
});




// Authenticated users
Route::middleware(['auth', 'PreventBackHistory', 'firewall.all'])->group(function () {

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'])->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'])->name('change-password');




    // Users Roles n Permissions
    Route::resource('users', App\Http\Controllers\Admin\UserController::class);
    Route::get('users/{user}/toggle', [App\Http\Controllers\Admin\UserController::class, 'toggle'])->name('users.toggle');
    Route::get('users/{user}/retire', [App\Http\Controllers\Admin\UserController::class, 'retire'])->name('users.retire');
    Route::put('users/{user}/change-password', [App\Http\Controllers\Admin\UserController::class, 'changePassword'])->name('users.change-password');
    Route::get('users/{user}/get-role', [App\Http\Controllers\Admin\UserController::class, 'getRole'])->name('users.get-role');
    Route::put('users/{user}/assign-role', [App\Http\Controllers\Admin\UserController::class, 'assignRole'])->name('users.assign-role');
    Route::resource('roles', App\Http\Controllers\Admin\RoleController::class);

    // Route for master
    Route::name('master.')->prefix('master/')->group(function () {
        Route::resource('department', DepartmentController::class);
        Route::resource('file-type', FileTypeController::class);
        Route::resource('financial-year', FinancialYearController::class);
        Route::resource('method', MethodController::class);
    });

    // file Route for forward
    Route::get('file/forward/get-department', [FileController::class, 'getForwardDepartment'])->name('file.forward-department');
    Route::get('file/forward/get-department-user', [FileController::class, 'getForwardDepartmentUser'])->name('file.forward-department-user');
    Route::get('file/forward/get-administrative-user', [FileController::class, 'getForwardAdministrativeUser'])->name('file.forward-administrative-user');
    Route::get('file/forward', [FileController::class, 'forward'])->name('file.forward');
    Route::get('file/show-forward-details', [FileController::class, 'showForwardDetails'])->name('files.showForwardDetails');
    Route::post('file/forward/store', [FileController::class, 'storeForward'])->name('file.storeForward');

    // file route for inward
    Route::get('file/inward', [FileController::class, 'inward'])->name('file.inward');
    Route::get('file/show-inward-details', [FileController::class, 'showInwardDetails'])->name('files.showInwardDetails');
    Route::post('file/inward/store', [FileController::class, 'storeInward'])->name('file.storeInward');

    // dmc file route
    Route::get('file/dmc/verify', [DMCFilePermissionController::class, 'index'])->name('dmcfile.index');
    Route::post('file/dmc-file/store', [DMCFilePermissionController::class, 'store'])->name('dmcfile.store');
    Route::get('file/dmc/verified', [DMCFilePermissionController::class, 'verified'])->name('dmcfile.verified');
    Route::get('file/dmc/rejected', [DMCFilePermissionController::class, 'rejected'])->name('dmcfile.rejected');

    // route for close file
    Route::get('file/close', [FileController::class, 'close'])->name('file.close');
    Route::post('file/close/store', [FileController::class, 'saveClose'])->name('file.saveClose');

    // file route for create
    Route::get('file/show-details', [FileController::class, 'showDetails'])->name('files.showDetails');
    Route::get('file/transit', [FileController::class, 'transit'])->name('files.transit');
    Route::get('file/qrcode', [FileController::class, 'qrCode'])->name('files.qrCode');
    Route::resource('file', FileController::class);

    // route for department file
    Route::get('department-files', [DepartmentFileController::class, 'getUserDepartmentFiles'])->name('department.getUserDepartmentFiles');

    // route for report
    Route::get('report/department', [ReportController::class, 'department'])->name('report.department');
    Route::get('report/employee', [ReportController::class, 'employee'])->name('report.employee');
    Route::get('report/file-status', [ReportController::class, 'fileStatus'])->name('report.fileStatus');
});




Route::get('/php', function (Request $request) {
    if (!auth()->check())
        return 'Unauthorized request';

    Artisan::call($request->artisan);
    return dd(Artisan::output());
});

app/Http/Controllers/Admin/Masters/WardController.php
<?php

namespace App\Http\Controllers\Admin\Masters;

use App\Http\Controllers\Admin\Controller;
use App\Http\Requests\Admin\Masters\StoreWardRequest;
use App\Http\Requests\Admin\Masters\UpdateWardRequest;
use App\Models\Ward;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;


class WardController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $wards = Ward::latest()->get();

        return view('admin.masters.wards')->with(['wards'=> $wards]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreWardRequest $request)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            Ward::create( Arr::only( $input, Ward::getFillables() ) );
            DB::commit();

            return response()->json(['success'=> 'Office created successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'creating', 'Office');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Ward $ward)
    {
        if ($ward)
        {
            $response = [
                'result' => 1,
                'ward' => $ward,
            ];
        }
        else
        {
            $response = ['result' => 0];
        }
        return $response;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateWardRequest $request, Ward $ward)
    {
        try
        {
            DB::beginTransaction();
            $input = $request->validated();
            $ward->update( Arr::only( $input, Ward::getFillables() ) );
            DB::commit();

            return response()->json(['success'=> 'Ward updated successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'updating', 'Ward');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Ward $ward)
    {
        try
        {
            DB::beginTransaction();
            $ward->delete();
            DB::commit();

            return response()->json(['success'=> 'Ward deleted successfully!']);
        }
        catch(\Exception $e)
        {
            return $this->respondWithAjax($e, 'deleting', 'Ward');
        }
    }
}

app/Http/Controllers/Master/DepartmentController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Master\DepartmentRequest;
use App\Services\Masters\DepartmentService;

class DepartmentController extends Controller
{
    protected $departmentService;

    public function __construct(DepartmentService $departmentService)
    {
        $this->departmentService = $departmentService;
    }

    public function index()
    {
        $departments = $this->departmentService->index();

        return view('master.department.index')->with(['departments' => $departments]);
    }

    public function store(DepartmentRequest $request)
    {
        $department = $this->departmentService->store($request);

        if ($department) {
            return response()->json(['success' => 'Department created successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }

    public function edit(Request $request, $id)
    {
        $department = $this->departmentService->edit($id);

        if ($department) {
            $response = [
                'result' => 1,
                'department' => $department,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(DepartmentRequest $request, $id)
    {
        $department = $this->departmentService->update($request, $id);

        if ($department) {
            return response()->json(['success' => 'Department updated successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }
}

app/Http/Controllers/Master/FileTypeController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Master\FileTypeRequest;
use App\Services\Masters\FileTypeService;

class FileTypeController extends Controller
{
    protected $fileTypeService;

    public function __construct(FileTypeService $fileTypeService)
    {
        $this->fileTypeService = $fileTypeService;
    }

    public function index()
    {
        $fileTypes = $this->fileTypeService->index();

        return view('master.file-type.index')->with(['fileTypes' => $fileTypes]);
    }

    public function store(FileTypeRequest $request)
    {
        $fileType = $this->fileTypeService->store($request);

        if ($fileType) {
            return response()->json(['success' => 'File type created successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }

    public function edit(Request $request, $id)
    {
        $fileType = $this->fileTypeService->edit($id);

        if ($fileType) {
            $response = [
                'result' => 1,
                'fileType' => $fileType,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    public function update(FileTypeRequest $request, $id)
    {
        $fileType = $this->fileTypeService->update($request, $id);

        if ($fileType) {
            return response()->json(['success' => 'File type updated successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }
}

app/Http/Controllers/Master/FinancialYearController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Master\FinancialYearRequest;
use App\Services\Masters\FinancialYearService;
use App\Models\FinancialYear;

class FinancialYearController extends Controller
{
    protected $financialYearService;

    public function __construct(FinancialYearService $financialYearService)
    {
        $this->financialYearService = $financialYearService;
    }

    public function index()
    {
        $financialYears = $this->financialYearService->index();

        return view('master.financial-year.index')->with(['financialYears' => $financialYears]);
    }

    public function store(FinancialYearRequest $request)
    {
        $fromDateCheck = FinancialYear::whereDate('from_date', '<=', date('Y-m-d', strtotime($request->from_date)))
            ->whereDate('to_date', '>=', date('Y-m-d', strtotime($request->from_date)))
            ->exists();

        $toDateCheck = FinancialYear::whereDate('from_date', '<=', date('Y-m-d', strtotime($request->to_date)))
            ->whereDate('to_date', '>=', date('Y-m-d', strtotime($request->to_date)))
            ->exists();
        if ($fromDateCheck || $toDateCheck) {
            return response()->json(['error' => 'Financial Year Already Exists!']);
        }

        $financialYear = $this->financialYearService->store($request);

        if ($financialYear) {
            return response()->json(['success' => 'Financial year created successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }

    public function edit(Request $request, $id)
    {
        $financialYear = $this->financialYearService->edit($id);

        if ($financialYear) {
            $response = [
                'result' => 1,
                'financialYear' => $financialYear,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    public function update(FinancialYearRequest $request, $id)
    {
        $fromDateCheck = FinancialYear::where('from_date', '<=', date('Y-m-d', strtotime($request->from_date)))
                ->where('to_date', '>=', date('Y-m-d', strtotime($request->from_date)))
                ->where('id', '!=', $request->edit_model_id)
                ->exists();

        $toDateCheck = FinancialYear::where('from_date', '<=', date('Y-m-d', strtotime($request->to_date)))
            ->where('to_date', '>=', date('Y-m-d', strtotime($request->to_date)))
            ->where('id', '!=', $request->edit_model_id)
            ->exists();

        if ($fromDateCheck || $toDateCheck) {
            return response()->json(['error' => 'Financial Year Already Exists!']);
        }

        $financialYear = $this->financialYearService->update($request, $id);

        if ($financialYear) {
            return response()->json(['success' => 'Financial year updated successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }
}

app/Http/Controllers/Master/MethodController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Master\MethodRequest;
use App\Services\Masters\MethodService;

class MethodController extends Controller
{
    protected $methodService;

    public function __construct(MethodService $methodService)
    {
        $this->methodService = $methodService;
    }

    public function index()
    {
        $methods = $this->methodService->index();

        return view('master.method.index')->with(['methods' => $methods]);
    }

    public function store(MethodRequest $request)
    {
        $method = $this->methodService->store($request);

        if ($method) {
            return response()->json(['success' => 'Method created successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }

    public function edit(Request $request, $id)
    {
        $method = $this->methodService->edit($id);

        if ($method) {
            $response = [
                'result' => 1,
                'method' => $method,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    public function update(MethodRequest $request, $id)
    {
        $method = $this->methodService->update($request, $id);

        if ($method) {
            return response()->json(['success' => 'Method updated successfully!']);
        } else {
            return response()->json(['error' => 'Something went wrong!']);
        }
    }
}

resources/views/master/file-type/index.blade.php
<x-admin.layout>
    <x-slot name="title">File Type</x-slot>
    <x-slot name="heading">File Type</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}

        @can('file-type.create')
        <!-- Add Form -->
        <div class="row" id="addContainer" style="display:none;">
            <div class="col-sm-12">
                <div class="card">
                    <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                        @csrf

                        <div class="card-header">
                            <h4 class="card-title">Add File Type</h4>
                        </div>
                        <div class="card-body">
                            <div class="mb-3 row">
                                <div class="col-md-4">
                                    <label class="col-form-label" for="name">Name <span class="text-danger">*</span></label>
                                    <input class="form-control" id="name" name="name" type="text" placeholder="Enter File Type Name">
                                    <span class="text-danger is-invalid name_err"></span>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label" for="status1">Status <span class="text-danger">*</span></label>
                                    <select name="status" class="form-select" id="status1">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                    <span class="text-danger is-invalid status_err"></span>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary" id="addSubmit">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @endcan


        @can('file-type.edit')
        {{-- Edit Form --}}
        <div class="row" id="editContainer" style="display:none;">
            <div class="col">
                <form class="form-horizontal form-bordered" method="post" id="editForm">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Edit File Type</h4>
                        </div>
                        <div class="card-body py-2">
                            <input type="hidden" id="edit_model_id" name="edit_model_id" value="">
                            <div class="mb-3 row">
                                <div class="col-md-4">
                                    <label class="col-form-label" for="name">Name <span class="text-danger">*</span></label>
                                    <input class="form-control" id="name" name="name" type="text" placeholder="File Type Name">
                                    <span class="text-danger is-invalid name_err"></span>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label" for="status1">Status <span class="text-danger">*</span></label>
                                    <select name="status" class="form-select" id="status1">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                    <span class="text-danger is-invalid status_err"></span>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary" id="editSubmit">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @endcan


        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    @can('file-type.create')
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="">
                                    <button id="addToTable" class="btn btn-primary">Add <i class="fa fa-plus"></i></button>
                                    <button id="btnCancel" class="btn btn-danger" style="display:none;">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endcan
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Name</th>
                                        <th>Status</th>
                                        @can('file-type.edit')<th>Action</th>@endcan
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($fileTypes as $fileType)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $fileType->name }}</td>
                                            <td>
                                                @if($fileType->status)
                                                <span class="badge bg-success">Active</span>
                                                @else
                                                <span class="badge bg-danger">Inactive</span>
                                                @endif
                                            </td>
                                            @can('file-type.edit')
                                            <td>
                                                <button class="edit-element btn text-secondary px-2 py-1" title="Edit file type" data-id="{{ $fileType->id }}"><i data-feather="edit"></i></button>
                                            </td>
                                            @endcan
                                        </tr>
                                    @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>




</x-admin.layout>


{{-- Add --}}
<script>
    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('master.file-type.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            beforeSend: function()
            {
                $('#preloader').css('opacity', '0.5');
                $('#preloader').css('visibility', 'visible');
            },
            success: function(data)
            {
                $("#addSubmit").prop('disabled', false);
                if (!data.error)
                    swal("Successful!", data.success, "success")
                        .then((action) => {
                            window.location.href = '{{ route('master.file-type.index') }}';
                        });
                else
                    swal("Error!", data.error, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            },
            complete: function() {
                $('#preloader').css('opacity', '0');
                $('#preloader').css('visibility', 'hidden');
            },
        });

    });
</script>


<!-- Edit -->
<script>
    $("#buttons-datatables").on("click", ".edit-element", function(e) {
        e.preventDefault();
        var model_id = $(this).attr("data-id");
        var url = "{{ route('master.file-type.edit', ":model_id") }}";

        $.ajax({
            url: url.replace(':model_id', model_id),
            type: 'GET',
            data: {
                '_token': "{{ csrf_token() }}"
            },
            beforeSend: function()
            {
                $('#preloader').css('opacity', '0.5');
                $('#preloader').css('visibility', 'visible');
            },
            success: function(data, textStatus, jqXHR) {
                editFormBehaviour();
                if (!data.error)
                {
                    $("#editForm input[name='edit_model_id']").val(data.fileType.id);
                    $("#editForm input[name='name']").val(data.fileType.name);
                    $("#editForm select[name='status']").val(data.fileType.status);
                }
                else
                {
                    alert(data.error);
                }
            },
            error: function(error, jqXHR, textStatus, errorThrown) {
                alert("Some thing went wrong");
            },
            complete: function() {
                $('#preloader').css('opacity', '0');
                $('#preloader').css('visibility', 'hidden');
            },
        });
    });
</script>


<!-- Update -->
<script>
    $(document).ready(function() {
        $("#editForm").submit(function(e) {
            e.preventDefault();
            $("#editSubmit").prop('disabled', true);
            var formdata = new FormData(this);
            formdata.append('_method', 'PUT');
            var model_id = $('#edit_model_id').val();
            var url = "{{ route('master.file-type.update', ":model_id") }}";
            //
            $.ajax({
                url: url.replace(':model_id', model_id),
                type: 'POST',
                data: formdata,
                contentType: false,
                processData: false,
                beforeSend: function()
                {
                    $('#preloader').css('opacity', '0.5');
                    $('#preloader').css('visibility', 'visible');
                },
                success: function(data)
                {
                    $("#editSubmit").prop('disabled', false);
                    if (!data.error)
                        swal("Successful!", data.success, "success")
                            .then((action) => {
                                window.location.href = '{{ route('master.file-type.index') }}';
                            });
                    else
                        swal("Error!", data.error, "error");
                },
                statusCode: {
                    422: function(responseObject, textStatus, jqXHR) {
                        $("#editSubmit").prop('disabled', false);
                        resetErrors();
                        printErrMsg(responseObject.responseJSON.errors);
                    },
                    500: function(responseObject, textStatus, errorThrown) {
                        $("#editSubmit").prop('disabled', false);
                        swal("Error occured!", "Something went wrong please try again", "error");
                    }
                },
                complete: function() {
                    $('#preloader').css('opacity', '0');
                    $('#preloader').css('visibility', 'hidden');
                },
            });

        });
    });
</script>